---
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: image-url-rewriter-webhook
version: 0.0.1
dependencies:
  - name: common
    repository: oci://sfbrdevhelmweacr.azurecr.io/helm
    version: 2025.1006.17
